apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: logging
spec:
  # selector:
  #   matchLabels:
  #     app: deis-logger-fluentd
  #     heritage: deis
  template:
    metadata:
      name: fluentd
      labels:
        component: fluentd
    spec:
      # serviceAccount: deis-logger-fluentd
      containers:
      - name: fluentd
        image: giantswarm/fluentd-kubernetes:0.1.1
        imagePullPolicy: IfNotPresent
        # imagePullPolicy: Always
        env:
        - name: DEBUG
          value: "true"
        volumeMounts:
        - name: config
          mountPath: /etc/fluent
        - name: host-var-log
          mountPath: /var/log
        - name: host-var-lib-docker-containers
          mountPath: /var/lib/docker/containers
          # readOnly: true
        - name: minikube-var-lib-docker-containers
          mountPath: /mnt/sda1/var/lib/docker/containers
      # terminationGracePeriodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: fluentd
      - name: host-var-log
        hostPath:
          path: /var/log
      - name: host-var-lib-docker-containers
        hostPath:
          path: /var/lib/docker/containers
      - name: minikube-var-lib-docker-containers
        hostPath:
          path: /mnt/sda1/var/lib/docker/containers
