apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: metricbeat
  labels:
    app: metricbeat
spec:
  template:
    metadata:
      name: metricbeat
      labels:
        app: metricbeat
    spec:
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:6.0.0-rc1
        imagePullPolicy: IfNotPresent
        args:
        - metricbeat
        - -e
        - -system.hostfs=/hostfs
        - -E
        - output.elasticsearch.username=elastic
        - -E
        - output.elasticsearch.password=changeme
        - -strict.perms=false
        resources: {}
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /usr/share/metricbeat/metricbeat.yml
          subPath: metricbeat.yml
        - name: config-modules
          mountPath: /usr/share/metricbeat/modules.d/
        # - name: hostfs-proc
        #   mountPath: /hostfs/proc
        #   readOnly: true
        # - name: hostfs-cgroup
        #   mountPath: /hostfs/sys/fs/cgroup
        #   readOnly: true
        - name: hostfs
          mountPath: /hostfs
          readOnly: true
        - name: hostfs-docker-sock
          mountPath: /var/run/docker.sock
          subPath: docker.sock
      # hostNetwork: true
      securityContext:
        fsGroup: 1000
      volumes:
      - name: config
        configMap:
          name: metricbeat
      - name: config-modules
        configMap:
          name: metricbeat-modules
      # - name: hostfs-proc
      #   hostPath:
      #     path: /proc
      # - name: hostfs-cgroup
      #   hostPath:
      #     path: /sys/fs/cgroup
      - name: hostfs
        hostPath:
          path: /
      - name: hostfs-docker-sock
        hostPath:
          path: /var/run
