apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat
  namespace: logging
  labels:
    component: filebeat
data:
  filebeat.yml: |
    filebeat.prospectors:
    - input_type: log
      paths:
      - /var/log/*.log

    - input_type: log
      paths:
      - /hostfs/var/lib/docker/containers/*/*-json.log
      tags:
      - docker
      json.keys_under_root: false
      json.message_key: log
      json.add_error_key: true
      # json.keys_under_root: true

    output.elasticsearch:
      hosts: ["elasticsearch:9200"]

      template.name: "filebeat"
      template.path: "filebeat.template.json"
      template.overwrite: false

    # Sets log level. The default log level is error.
    # Available log levels are: critical, error, warning, info, debug
    logging.level: info
