apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fluentd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: fluentd
    spec:
      containers:
      - image: gcr.io/google_containers/fluentd-elasticsearch:1.3
        name: fluentd
        env:
        - name: FLUENTD_ARGS
          value: -qq
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        volumeMounts:
        - name: containers
          mountPath: /var/lib/docker/containers
        - name: varlog
          mountPath: /varlog
        - name: config-volume
          mountPath: /etc/td-agent
      volumes:
      - name: containers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: config-volume
        configMap:
          name: fluentd
