apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-prospectors
  namespace: kube-system
  labels:
    app: filebeat
data:
  docker.yml: |
    # - type: log
    #   paths:
    #     - /hostfs/var/lib/docker/containers/*/*.log
    #   json.keys_under_root: true
    #   json.overwrite_keys: true
    #   close_inactive: 24h
    #   close_renamed: true
    #   pipeline: docker-logs
    #   processors:
    #     - add_kubernetes_metadata:
    #         in_cluster: true

  filebeat.yml: |
    - type: log
      paths:
        # - /hostfs/var/log/containers/*/*.log
        - /hostfs/var/lib/docker/containers/*/*.log
      json.keys_under_root: false
      json.overwrite_keys: false
      close_inactive: 24h
      close_renamed: true
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
