apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    app: filebeat
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
