apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-events
  namespace: logging
  labels:
    app: kube-events
spec:
  template:
    metadata:
      labels:
        app: kube-events
    spec:
      containers:
      - name: kube-events
        image: giantswarm/tiny-tools:0.1.0
        imagePullPolicy: IfNotPresent
        resources:
          # keep request = limit to keep this container in guaranteed class
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        env:
        - name: TERM
          value: xterm
        command:
        - fish
        - --command
        - |
          set kube_token (cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          # FIXME move `resource_version` to a volume
          touch ./resource_version
          while true
            set resource_version (cat ./resource_version)
            echo "starting with \$resource_version: $resource_version"

            curl --silent --fail --show-error --insecure --header "Authorization: Bearer $kube_token" \
              --request GET "https://kubernetes.default.svc/api/v1/watch/events?resourceVersion=$resource_version" \
                | while read -l event

              if test (echo $event | jq -r '.object.metadata.resourceVersion') = "null"
                echo "got \"null\""
                sleep 10
                break
              end

              set -l index "kube-events-"(date --utc -I)
              while not curl --silent --fail --show-error \
                --request POST http://elasticsearch.logging.svc:9200/$index/event --data "$event" \
                  | read -l es_result
                echo "\$status: $status"
                sleep 10
              end

              set resource_version (echo $event | jq -r '.object.metadata.resourceVersion')
              echo $resource_version > ./resource_version
              echo "last fetched \$resource_version: $resource_version"
            end

            echo "starting over"
          end
